name: Deploy on server
on:
  workflow_run:
    workflows: [Node.js CI]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      REACT_APP_MONGOURI: ${{ secrets.REACT_APP_MONGOURI }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init cs3219-otot --platform node.js --region ${{ secrets.AWS_DEFAULT_REGION }}
          eb deploy Cs3219otot-env
